### ISSUE TITLE
Support the use command?

### ISSUE THREAD

**Issue by connorlay** [LineWeight/voya.js#3]
A lot of text adventures allow players to `use` an item in their inventory to some effect. Currently the `drop` command allows players to use an item (such as purchasing a ticket with a dollar in the Carnival game), but that seems counter intuitive as dropping something usually indicates discarding an item, rather than using it for some benefit.

An example I was thinking of:
`$ use dollar on ticket stand`
`=> You purchase a ticket with the dollar. You can now enter the main square!`

This is a really cool project!

**Comment by trevorsargent** [comment]
that's really helpful! I'm not super familiar with patterns as i don't actually spend a ton of time playing them myself 🤣 that also simplifies/expends logical possibilities in terms of locking mechanisms and payment etc.

**Comment by trevorsargent** [comment]
implemented on master, the engine is still bare but the command is there
